-- AlterTable
ALTER TABLE "reviews" ALTER COLUMN "rating" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "tutor_profiles" ALTER COLUMN "pricePerHour" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "experience" SET DATA TYPE DOUBLE PRECISION;
